POST http://localhost:8080/register
Content-Type: application/x-www-form-urlencoded

name=Poulet&url=http://localhost:8081&redirect_success=http://localhost:8081/callback

###
GET http://localhost:8080/auth?state=yes&client_id=621f5a60e7aaa&scope=public_profile&redirect_uri=http://localhost:8081/callback&response_type=code

###
GET http://localhost:8080/token?code=8556e7e84b8f92c6358ddcd0728268fa&client_id=621f5a60e7aaa&scope=public_profile&redirect_uri=http://localhost:8081/callback&grant_type=authorisation_code&client_secret=621f5a60e7aaa&client_secret=621f5a60e7ab5

###
GET http://localhost:8080/token?client_id=621f5a60e7aaa&scope=public_profile&redirect_uri=http://localhost:8081/callback&grant_type=password&client_id=621f5a60e7aaa&username=poulet_roti&password=1646325332&user_id=c9588ca022bd67d0738b96c6d8342eba
